### PR TITLE
Update to KDE Runtime 6.6

### PR DESCRIPTION
**Pull request by travier**
Fixes: https://github.com/flathub/org.kde.kid3/issues/15

### CODE REVIEW

**Comment by notfirefox** [comment]
I tried the 106890 build and can confirm the issue that @ufleisch [mentioned](https://github.com/flathub/org.kde.kid3/issues/15#issuecomment-1995583570).

> However, when I build the Kid3 flatpak like this, the resulting application has only the standard actions in its menu, i.e. not a lot of actions.

**Runtime 5**
image

**Runtime 6**
image

**Comment by travier** [comment]
Hum, I still have the same error. Weird, will investigate.

**Comment by ufleisch** [comment]
I have to revise my statement from https://github.com/flathub/org.kde.kid3/issues/15#issuecomment-1995583570, the KDE 6 port in Arch Linux is only working because I still have a UI configuration in _~/.local/share/kxmlgui5/kid3/kid3ui.rc_, if I remove this file, I get the same behavior as with the KDE6 flatpak, i.e. only the standard actions in the menu and the toolbars. Also the non-flatpak application searches in the following paths

- /home/urs/.local/share/kxmlgui5/kid3/kid3ui.rc
- /home/urs/.local/share/flatpak/exports/share/kxmlgui5/kid3/kid3ui.rc
- /var/lib/flatpak/exports/share/kxmlgui5/kid3/kid3ui.rc
- /usr/local/share/kxmlgui5/kid3/kid3ui.rc
- /usr/share/kxmlgui5/kid3/kid3ui.rc

It seems that the kxmlgui5 name has been kept for compatibility/migration reasons (I have also verified these locations with `konsole`). So I would expect that it will work if you do not remove the whole hack at the end of _src/app/kde/CMakeLists.txt_ but only change `kxmlgui6` to `kxmlgui5`.

**Comment by notfirefox** [comment]
> Build [107127 successful](https://buildbot.flathub.org/#/builders/6/builds/107127) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/89945/org.kde.kid3.flatpakref
> ```

Looks good to me!

**Comment by travier** [comment]
Looks like this one is working (at least it fixed the issue mentionned)!

**Comment by ufleisch** [comment]
Thanks for your contribution. I just replaced your patch with one I committed upstream, which does basically the same but also works with old KDE versions, so it is clear that the patch is no longer needed with the next Kid3 release and it is linked to the corresponding bug I reported on the KDE bugzilla.

- https://invent.kde.org/multimedia/kid3/-/commit/b3c65a8c1a3a4d6fe5655a5c2bf1c9e7eabb7ffb
- https://bugs.kde.org/show_bug.cgi?id=483766

**Pull request merged**
